name: Deploy to Locaweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Install Node dependencies and build assets
        run: |
          npm ci
          npm run build

      - name: Create deployment archive
        run: |
          tar -czf /tmp/deploy.tar.gz \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='tests' \
            --exclude='.env' \
            --exclude='storage/app/*' \
            --exclude='storage/framework/cache/*' \
            --exclude='storage/framework/sessions/*' \
            --exclude='storage/framework/testing/*' \
            --exclude='storage/framework/views/*' \
            --exclude='storage/logs/*' \
            --exclude='deploy.tar.gz' \
            .
          mv /tmp/deploy.tar.gz .

      - name: Deploy to Locaweb via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy.tar.gz,deploy.sh"
          target: "~/deploy_temp"

      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy_temp
            chmod +x deploy.sh
            ./deploy.sh
            rm -rf ~/deploy_temp

      - name: Notify deployment success
        if: success()
        run: echo "✅ Deployment completed successfully!"

      - name: Notify deployment failure
        if: failure()
        run: echo "❌ Deployment failed!"
